Feature : Resource State Events
NARKOZ/gitlab pull request #580
Opened 2020-08-31 10:35 UTC by dinesh-hd

Resource state events represent the states that the MR or Issue has transitioned in its life time.
This allows us to track, which state was set, who did it, and when it happened.

1. Resource state events api's added
2. Linking resoruce state event module into client.rb

Resource state event api added in Gitlab 3.2

More information [here](https://docs.gitlab.com/13.2/ee/api/resource_state_events.html#list-project-merge-request-state-events)

2020-08-31 20:16 UTC, NARKOZ requested changes
Could you add tests for this feature?

2020-08-31 20:25 UTC, dinesh-hd commented
> Could you add tests for this feature?

Sure. Will get this done

2020-09-01 07:09 UTC, dinesh-hd commented
@NARKOZ Tests added

2020-09-01 08:06 UTC, NARKOZ approved these changes

2020-09-01 08:06 UTC, merged

2020-09-01 08:06 UTC, NARKOZ commented
Thank you ❤️